import tokens from 'constants/tokens'

export const sortTypeFarms = {
  hot: 'hot',
  apr: 'apr',
  tvl: 'tvl',
}

export const sortListFarms = [
  {
    name: sortTypeFarms.hot,
    label: 'Hot',
  },
  {
    name: sortTypeFarms.apr,
    label: 'Apr',
  },
  {
    name: sortTypeFarms.tvl,
    label: 'Tvl',
  },
]

export const farmsConfig = [
  {
    pid: 0,
    lpAddress: tokens.wkai.address,
    token0: tokens.wkai,
    allocPoint: '100',
    symbol: 'WKAI',
    icon: 'kai.png',
  },
  {
    pid: 1,
    lpAddress: '0xfb62ae373aca027177d1c18ee0862817f9080d08',
    token0: tokens.dpet,
    allocPoint: '25',
    symbol: 'DPET',
    icon: 'dpet.png',
  },
  {
    pid: 6,
    lpAddress: tokens.dragon.address,
    token0: tokens.dragon,
    allocPoint: '2000',
    symbol: tokens.dragon.symbol,
    icon: 'dragon.png',
  },
  {
    pid: 3,
    lpAddress: '0x7cd3c7afedd16a72fba66ea35b2e2b301d1b7093',
    allocPoint: '100',
    symbol: 'KLP',
    token0: tokens.kusd,
    token1: tokens.wkai,
    icon: 'kusd-t.png',
  },
  {
    pid: 4,
    lpAddress: '0xdb504f611ae0230bdc60a8f58fe89d3593eb28ce',
    allocPoint: '25',
    symbol: 'KLP',
    token0: tokens.wkai,
    token1: tokens.dpet,
    icon: 'kai.png',
  },
  {
    pid: 5,
    lpAddress: '0x256b8a99f69dbdbb5ac781e97f11080a336f5507',
    allocPoint: '4000',
    symbol: 'KLP',
    token0: tokens.wkai,
    token1: tokens.defily,
  },
  {
    pid: 7,
    lpAddress: '0x5b60a5761047b3a9ec340941d904231be85f5c0b',
    allocPoint: '100',
    symbol: 'KLP',
    token0: tokens.bossDogev2,
    token1: tokens.wkai,
    icon: 'bossdoge.png',
  },
  {
    pid: 2,
    lpAddress: tokens.defily.address,
    token0: tokens.defily,
    allocPoint: '1',
    symbol: 'DFL',
  },
  {
    pid: 8,
    lpAddress: '0x1f95bD3A7d5c9DF6bF56504bbA948A7ADF1c3e27',
    allocPoint: '100',
    symbol: 'KLP',
    token0: tokens.wkai,
    token1: tokens.ltd,
    icon: 'ltd.png',
  },
  {
    pid: 9,
    lpAddress: '0x3e82F9290A28D4296d34d0c1e6E5366c4220248a',
    allocPoint: '3000',
    symbol: 'KLP',
    token0: tokens.kusd,
    token1: tokens.defily,
  },
  {
    pid: 10,
    lpAddress: tokens.bossDogev2.address,
    allocPoint: '100',
    token0: tokens.bossDogev2,
    symbol: tokens.bossDogev2.symbol,
    decimals: tokens.bossDogev2.decimals,
    icon: 'bossdoge.png',
  },
  {
    pid: 11,
    lpAddress: '0x6c98542a41b820491a4a8B7a71dA26b8eA524b07',
    allocPoint: '100',
    symbol: 'KLP',
    token0: tokens.nami,
    token1: tokens.wkai,
    icon: 'nami.png',
  },
  {
    pid: 12,
    lpAddress: tokens.nami.address,
    token0: tokens.nami,
    allocPoint: '100',
    symbol: tokens.nami.symbol,
    icon: 'nami.png',
  },
  {
    pid: 13,
    lpAddress: tokens.ltd.address,
    token0: tokens.ltd,
    symbol: tokens.ltd.symbol,
    allocPoint: '100',
    icon: 'ltd.png',
  },
  {
    pid: 14,
    lpAddress: '0x5D6724F4ac40AEb1A47b9CcFe293363D100d4e5f',
    allocPoint: '100',
    symbol: 'KLP',
    token0: tokens.lpdi,
    token1: tokens.kusd,
    icon: 'lpdi.png',
  },
  {
    pid: 15,
    lpAddress: tokens.lpdi.address,
    token0: tokens.lpdi,
    allocPoint: '100',
    symbol: tokens.lpdi.symbol,
    icon: 'lpdi.png',
  },
  {
    pid: 16,
    lpAddress: '0xD17459b9CFc1D7010f7538F123Cd68f8aB042e12',
    allocPoint: '100',
    symbol: 'KLP',
    token0: tokens.lpdi,
    token1: tokens.wkai,
    icon: 'lpdi.png',
  },
  {
    pid: 17,
    lpAddress: tokens.kusd.address,
    allocPoint: '50',
    token0: tokens.kusd,
    symbol: tokens.kusd.symbol,
    icon: 'kusd-t.png',
  },
  {
    pid: 18,
    lpAddress: tokens.vndc.address,
    symbol: tokens.vndc.symbol,
    allocPoint: '50',
    token0: tokens.vndc,
    icon: 'vndc.png',
  },
  {
    pid: 19,
    lpAddress: tokens.vndt.address,
    symbol: tokens.vndt.symbol,
    allocPoint: '25',
    token0: tokens.vndt,
    icon: 'vndt.png',
  },
  {
    pid: 20,
    lpAddress: tokens.wDragon.address,
    symbol: tokens.wDragon.symbol,
    allocPoint: '300',
    token0: tokens.wDragon,
    icon: 'dragon.png',
  },
  {
    pid: 21,
    lpAddress: '0x05D6aE694d44B4005aCBF18a701ec7C84CDB82Df',
    allocPoint: '100',
    symbol: 'KLP',
    token0: tokens.chat,
    token1: tokens.kusd,
    icon: 'chat.png',
  },
  {
    pid: 22,
    lpAddress: tokens.chat.address,
    symbol: tokens.chat.symbol,
    allocPoint: '100',
    token0: tokens.chat,
    icon: 'chat.png',
  },
  {
    pid: 23,
    lpAddress: tokens.gdt.address,
    symbol: tokens.gdt.symbol,
    allocPoint: '200',
    token0: tokens.gdt,
    icon: 'gdt.png',
  },
  {
    pid: 24,
    lpAddress: '0xc56577c105e76463F32239c8222FbbfD45383aFA',
    allocPoint: '100',
    symbol: 'KLP',
    token0: tokens.gdt,
    token1: tokens.kusd,
    icon: 'gdt.png',
  },
  {
    pid: 25,
    lpAddress: '0x5D374efF61e799470b88da02Ab73899e60246fa4',
    allocPoint: '100',
    symbol: 'KLP',
    token0: tokens.gdt,
    token1: tokens.wkai,
    icon: 'gdt.png',
  },
  // {
  //   pid: 23,
  //   lpAddress: tokens.eth.address,
  //   symbol: tokens.eth.symbol,
  //   allocPoint: '100',
  //   token0: tokens.eth,
  //   icon: 'eth.png',
  // },
]

export default farmsConfig
